strategy:
  matrix:
    linux:
      imageName: 'ubuntu-16.04'
    mac:
      imageName: 'macos-10.13'
    windows:
      imageName: 'Windows-2019'

pr:
- master

trigger:
- master

pool:
  vmImage: $(imageName)

variables:
  LoggingOptions: '-Dorg.slf4j.simpleLogger.defaultLogLevel=error -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn'

steps:
- task: Maven@3
  displayName: 'package'
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'package'
    options: 'javadoc:aggregate -DpackageOutputDirectory=$(Build.ArtifactStagingDirectory)" -am'
    mavenOptions: '$(LoggingOptions)'
    publishJUnitResults: true 
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    findBugsRunAnalysis: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))